/**
 * Complete in-browser standalone demo dataset and calculation engine for Decarbo.
 * Allows the entire Jamnagar Brass Demo to run instantly and offline with zero backend lag.
 */

export const DEMO_FACTORY_ID = "demo-jamnagar-brass";

export const DEMO_FACTORY = {
  id: DEMO_FACTORY_ID,
  name: "Sample Brass Components (Jamnagar Demo)",
  industry: "brass_components",
  products: "Precision turned brass components and inserts",
  city: "Jamnagar",
  state: "Gujarat",
  cluster: "Jamnagar Brass",
  grid_region: "IN-GJ",
  output_unit: "t",
  annual_output: 540,
  electricity_tariff_inr_per_kwh: 7.8,
  created_at: "2025-04-01T00:00:00Z",
};

export const DEMO_DASHBOARD_DATA = {
  factory_id: DEMO_FACTORY_ID,
  factory_name: "Sample Brass Components (Jamnagar Demo)",
  industry: "brass_components",
  city: "Jamnagar",
  state: "Gujarat",
  cluster: "Jamnagar Brass",
  has_data: true,
  period_start: "2025-04-01",
  period_end: "2026-03-31",

  // Top Strip Metrics
  annual_tco2e: 428.6,
  intensity_tco2e_per_tonne_output: 0.79,
  kwh_per_tonne_output: 412.5,
  estimated_factor_pct: 7.4,
  data_quality_label: "high",

  // Scope Totals
  scope1_tco2e: 82.4,
  scope2_tco2e: 296.2,
  scope3_tco2e: 50.0,

  // Sankey Energy & Emissions Flows
  sankey: {
    nodes: [
      { name: "Grid Electricity (PGVCL)", itemStyle: { color: "#2D7A57" } },
      { name: "Diesel Genset (Backup)", itemStyle: { color: "#A97A2B" } },
      { name: "LPG / PNG (Annealing)", itemStyle: { color: "#B5432C" } },
      { name: "Brass Scrap & Ingots", itemStyle: { color: "#5A6478" } },
      { name: "Induction Melting Furnaces", itemStyle: { color: "#1D2A45" } },
      { name: "CNC & Turning Centers", itemStyle: { color: "#1D2A45" } },
      { name: "Compressed Air Network", itemStyle: { color: "#1D2A45" } },
      { name: "Annealing & Heat Treatment", itemStyle: { color: "#1D2A45" } },
      { name: "Scope 1 Direct Emissions", itemStyle: { color: "#B5432C" } },
      { name: "Scope 2 Indirect Electricity", itemStyle: { color: "#A97A2B" } },
      { name: "Scope 3 Raw Materials & Freight", itemStyle: { color: "#2D7A57" } },
    ],
    links: [
      { source: "Grid Electricity (PGVCL)", target: "Induction Melting Furnaces", value: 165.8 },
      { source: "Grid Electricity (PGVCL)", target: "CNC & Turning Centers", value: 72.4 },
      { source: "Grid Electricity (PGVCL)", target: "Compressed Air Network", value: 58.0 },
      { source: "Diesel Genset (Backup)", target: "CNC & Turning Centers", value: 24.2 },
      { source: "LPG / PNG (Annealing)", target: "Annealing & Heat Treatment", value: 58.2 },
      { source: "Brass Scrap & Ingots", target: "Induction Melting Furnaces", value: 50.0 },
      { source: "Induction Melting Furnaces", target: "Scope 2 Indirect Electricity", value: 165.8 },
      { source: "CNC & Turning Centers", target: "Scope 2 Indirect Electricity", value: 72.4 },
      { source: "CNC & Turning Centers", target: "Scope 1 Direct Emissions", value: 24.2 },
      { source: "Compressed Air Network", target: "Scope 2 Indirect Electricity", value: 58.0 },
      { source: "Annealing & Heat Treatment", target: "Scope 1 Direct Emissions", value: 58.2 },
      { source: "Brass Scrap & Ingots", target: "Scope 3 Raw Materials & Freight", value: 50.0 },
    ],
    table_rows: [
      { pool: "Grid Electricity (PGVCL)", process: "Induction Melting Furnaces", emissions_tco2e: 165.8, share_pct: 38.7 },
      { pool: "Grid Electricity (PGVCL)", process: "CNC & Turning Centers", emissions_tco2e: 72.4, share_pct: 16.9 },
      { pool: "Grid Electricity (PGVCL)", process: "Compressed Air Network", emissions_tco2e: 58.0, share_pct: 13.5 },
      { pool: "LPG / PNG (Annealing)", process: "Annealing & Heat Treatment", emissions_tco2e: 58.2, share_pct: 13.6 },
      { pool: "Brass Scrap & Ingots", process: "Raw Material Logistics", emissions_tco2e: 50.0, share_pct: 11.7 },
      { pool: "Diesel Genset (Backup)", process: "Emergency Backup Power", emissions_tco2e: 24.2, share_pct: 5.6 },
    ],
  },

  // Pareto Leak Points
  leak_points: [
    {
      rank: 1,
      activity_type: "grid_electricity",
      name: "Compressed Air Distribution Leaks",
      scope: "scope2",
      category: "electricity",
      tco2e: 24.6,
      pct_of_total: 5.7,
      cumulative_pct: 5.7,
      is_pareto_leakpoint: true,
      best_fix: {
        title: "Compressed-air ultrasonic leak audit & automatic drain valves",
        description: "Acoustic detection of 18 leak points across main ring header and drop lines",
        capex_inr: 45000,
        annual_savings_inr: 192000,
        payback_str: "2.8 months",
        cuts_pct: 5.7,
      },
    },
    {
      rank: 2,
      activity_type: "grid_electricity",
      name: "Induction Furnace Refractory Heat Loss",
      scope: "scope2",
      category: "electricity",
      tco2e: 18.2,
      pct_of_total: 4.2,
      cumulative_pct: 9.9,
      is_pareto_leakpoint: true,
      best_fix: {
        title: "High-alumina ceramic fiber insulation lining for crucible",
        description: "Replaces worn ramming mass with lightweight low thermal-mass backing",
        capex_inr: 120000,
        annual_savings_inr: 240000,
        payback_str: "6.0 months",
        cuts_pct: 4.2,
      },
    },
    {
      rank: 3,
      activity_type: "grid_electricity",
      name: "Non-VFD Fixed Speed Air Compressors",
      scope: "scope2",
      category: "electricity",
      tco2e: 15.4,
      pct_of_total: 3.6,
      cumulative_pct: 13.5,
      is_pareto_leakpoint: true,
      best_fix: {
        title: "Variable Frequency Drive (VFD) retrofit on 37kW screw compressor",
        description: "Eliminates off-load idling power consumption by modulating motor speed with air demand",
        capex_inr: 185000,
        annual_savings_inr: 210000,
        payback_str: "10.5 months",
        cuts_pct: 3.6,
      },
    },
    {
      rank: 4,
      activity_type: "fuel_lpg",
      name: "Annealing Furnace Flue Gas Heat Waste",
      scope: "scope1",
      category: "fuel",
      tco2e: 14.1,
      pct_of_total: 3.3,
      cumulative_pct: 16.8,
      is_pareto_leakpoint: true,
      best_fix: {
        title: "Metallic recuperator for combustion air preheating (300°C)",
        description: "Recovers exhaust heat to preheat incoming burner air, cutting fuel usage by 18%",
        capex_inr: 260000,
        annual_savings_inr: 215000,
        payback_str: "14.5 months",
        cuts_pct: 3.3,
      },
    },
  ],

  // 14% Drift Alert in Jamnagar Brass
  drift_alerts: [
    {
      activity_type: "grid_electricity",
      percentage_change: 14.2,
      period_start: "2026-01-01",
      period_end: "2026-03-31",
      severity: "high",
      message: "Electricity intensity drifted +14.2% above the 9-month baseline (412 vs 361 kWh/t).",
      recommendation:
        "Root cause identified: Compressor #2 pressure switch stuck at 8.2 bar off-load, causing continuous unloader cycling. Check air intake filters and pressure setpoints.",
    },
  ],

  // Provenance Audit Items
  provenance_items: [
    {
      id: "prov-001",
      activity_type: "grid_electricity",
      activity_name: "PGVCL HT Tariff IV Industrial Power",
      period: "2026-03",
      scope: "scope2",
      quantity: 34500,
      unit: "kWh",
      quantity_canonical: 34500,
      canonical_unit: "kWh",
      factor_name: "CEA CO2 Baseline Database for the Indian Power Sector",
      factor_source: "Central Electricity Authority (CEA)",
      factor_version: "v21.0",
      factor_year: 2024,
      factor_value: 0.71,
      factor_unit: "kgCO2e/kWh",
      formula: "34,500 kWh × 0.710 kgCO2e/kWh ÷ 1,000 = 24.50 tCO2e",
      kgco2e: 24495,
      tco2e: 24.5,
      verified: true,
    },
    {
      id: "prov-002",
      activity_type: "diesel_dg",
      activity_name: "High Speed Diesel (HSD) for DG Backup",
      period: "2026-03",
      scope: "scope1",
      quantity: 850,
      unit: "L",
      quantity_canonical: 850,
      canonical_unit: "L",
      factor_name: "IPCC 2006 Guidelines for National GHG Inventories",
      factor_source: "IPCC / MoEFCC",
      factor_version: "2006 IPCC Vol 2",
      factor_year: 2021,
      factor_value: 2.68,
      factor_unit: "kgCO2e/L",
      formula: "850 L × 2.680 kgCO2e/L ÷ 1,000 = 2.28 tCO2e",
      kgco2e: 2278,
      tco2e: 2.28,
      verified: true,
    },
  ],

  // Circularity Score
  circularity: {
    score_pct: 82,
    grade: "B+",
    recycled_input_ratio: 0.82,
    scrap_utilization_ratio: 0.91,
    swarf_recovery_pct: 95,
    points_earned: 14,
    points_max: 20,
    highlights: [
      "In-house swarf briquetting eliminates oxidation losses in melting",
      "82% recycled brass honey scrap utilized in core charge",
      "Dry-cutting lubricant separation active on 6 CNC lathes",
    ],
  },
};

export const DEMO_PLANS_DATA = {
  plans: [
    {
      id: "plan-quick-wins",
      mode: "quick_wins",
      label: "Quick Wins (< 6 mo payback)",
      feasible: true,
      message: null,
      is_selected: true,
      totals: {
        capex_inr: 165000,
        annual_savings_inr: 432000,
        reduction_tco2e: 42.8,
        reduction_pct: 10.0,
        average_payback_months: 4.6,
        circularity_points: 4,
      },
      ledger: [
        {
          id: "item-1",
          sequence: 1,
          intervention_code: "CA_LEAK_FIX",
          title_en: "Compressed-air distribution leak audit & seal overhaul",
          category: "electricity",
          pool: "grid_electricity",
          difficulty: 1,
          circularity_points: 1,
          capex_inr: 45000,
          annual_savings_inr: 192000,
          reduction_kgco2e: 24600,
          reduction_tco2e: 24.6,
          payback_months: 2.8,
          cost_per_tonne_inr: -7805,
          added_grid_kwh: 0,
        },
        {
          id: "item-2",
          sequence: 2,
          intervention_code: "CRUCIBLE_INSULATION",
          title_en: "Induction furnace ceramic fiber thermal insulation jacket",
          category: "electricity",
          pool: "grid_electricity",
          difficulty: 1,
          circularity_points: 1,
          capex_inr: 120000,
          annual_savings_inr: 240000,
          reduction_kgco2e: 18200,
          reduction_tco2e: 18.2,
          payback_months: 6.0,
          cost_per_tonne_inr: -6593,
          added_grid_kwh: 0,
        },
      ],
      uncertainty: {
        savings_p10_inr: 390000,
        savings_p90_inr: 475000,
        payback_p10_months: 4.2,
        payback_p90_months: 5.1,
      },
    },
    {
      id: "plan-low-capex",
      mode: "low_capex",
      label: "Low Capex (₹5 Lakhs Cap)",
      feasible: true,
      message: null,
      is_selected: false,
      totals: {
        capex_inr: 470000,
        annual_savings_inr: 722000,
        reduction_tco2e: 68.4,
        reduction_pct: 16.0,
        average_payback_months: 7.8,
        circularity_points: 7,
      },
      ledger: [
        {
          id: "item-1",
          sequence: 1,
          intervention_code: "CA_LEAK_FIX",
          title_en: "Compressed-air distribution leak audit & seal overhaul",
          category: "electricity",
          pool: "grid_electricity",
          difficulty: 1,
          circularity_points: 1,
          capex_inr: 45000,
          annual_savings_inr: 192000,
          reduction_kgco2e: 24600,
          reduction_tco2e: 24.6,
          payback_months: 2.8,
          cost_per_tonne_inr: -7805,
          added_grid_kwh: 0,
        },
        {
          id: "item-2",
          sequence: 2,
          intervention_code: "CRUCIBLE_INSULATION",
          title_en: "Induction furnace ceramic fiber thermal insulation jacket",
          category: "electricity",
          pool: "grid_electricity",
          difficulty: 1,
          circularity_points: 1,
          capex_inr: 120000,
          annual_savings_inr: 240000,
          reduction_kgco2e: 18200,
          reduction_tco2e: 18.2,
          payback_months: 6.0,
          cost_per_tonne_inr: -6593,
          added_grid_kwh: 0,
        },
        {
          id: "item-3",
          sequence: 3,
          intervention_code: "VFD_COMPRESSOR",
          title_en: "Variable Frequency Drive (VFD) retrofit on 37kW screw compressor",
          category: "electricity",
          pool: "grid_electricity",
          difficulty: 2,
          circularity_points: 2,
          capex_inr: 185000,
          annual_savings_inr: 210000,
          reduction_kgco2e: 15400,
          reduction_tco2e: 15.4,
          payback_months: 10.5,
          cost_per_tonne_inr: -13636,
          added_grid_kwh: 0,
        },
        {
          id: "item-4",
          sequence: 4,
          intervention_code: "LED_HIGHBAY",
          title_en: "Shop floor 150W highbay lighting transition to 60W smart LED",
          category: "electricity",
          pool: "grid_electricity",
          difficulty: 1,
          circularity_points: 1,
          capex_inr: 120000,
          annual_savings_inr: 80000,
          reduction_kgco2e: 10200,
          reduction_tco2e: 10.2,
          payback_months: 18.0,
          cost_per_tonne_inr: -7843,
          added_grid_kwh: 0,
        },
      ],
      uncertainty: {
        savings_p10_inr: 660000,
        savings_p90_inr: 780000,
        payback_p10_months: 7.2,
        payback_p90_months: 8.5,
      },
    },
    {
      id: "plan-balanced",
      mode: "balanced",
      label: "Balanced (Recommended)",
      feasible: true,
      message: null,
      is_selected: false,
      totals: {
        capex_inr: 1250000,
        annual_savings_inr: 1480000,
        reduction_tco2e: 142.6,
        reduction_pct: 33.3,
        average_payback_months: 10.1,
        circularity_points: 12,
      },
      ledger: [
        {
          id: "item-1",
          sequence: 1,
          intervention_code: "CA_LEAK_FIX",
          title_en: "Compressed-air distribution leak audit & seal overhaul",
          category: "electricity",
          pool: "grid_electricity",
          difficulty: 1,
          circularity_points: 1,
          capex_inr: 45000,
          annual_savings_inr: 192000,
          reduction_kgco2e: 24600,
          reduction_tco2e: 24.6,
          payback_months: 2.8,
          cost_per_tonne_inr: -7805,
          added_grid_kwh: 0,
        },
        {
          id: "item-2",
          sequence: 2,
          intervention_code: "CRUCIBLE_INSULATION",
          title_en: "Induction furnace ceramic fiber thermal insulation jacket",
          category: "electricity",
          pool: "grid_electricity",
          difficulty: 1,
          circularity_points: 1,
          capex_inr: 120000,
          annual_savings_inr: 240000,
          reduction_kgco2e: 18200,
          reduction_tco2e: 18.2,
          payback_months: 6.0,
          cost_per_tonne_inr: -6593,
          added_grid_kwh: 0,
        },
        {
          id: "item-3",
          sequence: 3,
          intervention_code: "SOLAR_ROOFTOP_80KW",
          title_en: "80 kWp On-site Solar PV Rooftop Installation (Net Metered)",
          category: "onsite_solar",
          pool: "grid_electricity",
          difficulty: 2,
          circularity_points: 3,
          capex_inr: 780000,
          annual_savings_inr: 838000,
          reduction_kgco2e: 84400,
          reduction_tco2e: 84.4,
          payback_months: 11.2,
          cost_per_tonne_inr: -9928,
          added_grid_kwh: 0,
        },
        {
          id: "item-4",
          sequence: 4,
          intervention_code: "RECUPERATOR_FLUE",
          title_en: "Metallic recuperator for combustion air preheating on annealing line",
          category: "fuel",
          pool: "fuel_lpg",
          difficulty: 2,
          circularity_points: 2,
          capex_inr: 305000,
          annual_savings_inr: 210000,
          reduction_kgco2e: 15400,
          reduction_tco2e: 15.4,
          payback_months: 17.4,
          cost_per_tonne_inr: -13636,
          added_grid_kwh: 0,
        },
      ],
      uncertainty: {
        savings_p10_inr: 1350000,
        savings_p90_inr: 1610000,
        payback_p10_months: 9.3,
        payback_p90_months: 11.0,
      },
    },
    {
      id: "plan-max-reduction",
      mode: "max_reduction",
      label: "Maximum Reduction (Net Zero Pathway)",
      feasible: true,
      message: null,
      is_selected: false,
      totals: {
        capex_inr: 2850000,
        annual_savings_inr: 2340000,
        reduction_tco2e: 218.6,
        reduction_pct: 51.0,
        average_payback_months: 14.6,
        circularity_points: 18,
      },
      ledger: [
        {
          id: "item-1",
          sequence: 1,
          intervention_code: "CA_LEAK_FIX",
          title_en: "Compressed-air distribution leak audit & seal overhaul",
          category: "electricity",
          pool: "grid_electricity",
          difficulty: 1,
          circularity_points: 1,
          capex_inr: 45000,
          annual_savings_inr: 192000,
          reduction_kgco2e: 24600,
          reduction_tco2e: 24.6,
          payback_months: 2.8,
          cost_per_tonne_inr: -7805,
          added_grid_kwh: 0,
        },
        {
          id: "item-2",
          sequence: 2,
          intervention_code: "SOLAR_ROOFTOP_150KW",
          title_en: "150 kWp High-efficiency Mono PERC Solar Rooftop with Battery Backup",
          category: "onsite_solar",
          pool: "grid_electricity",
          difficulty: 3,
          circularity_points: 4,
          capex_inr: 1550000,
          annual_savings_inr: 1420000,
          reduction_kgco2e: 142000,
          reduction_tco2e: 142.0,
          payback_months: 13.1,
          cost_per_tonne_inr: -10000,
          added_grid_kwh: 0,
        },
        {
          id: "item-3",
          sequence: 3,
          intervention_code: "ELECTRIC_ANNEALING",
          title_en: "Electrification of LPG annealing furnace with high-temp induction coils",
          category: "electrification",
          pool: "fuel_lpg",
          difficulty: 3,
          circularity_points: 3,
          capex_inr: 850000,
          annual_savings_inr: 418000,
          reduction_kgco2e: 36600,
          reduction_tco2e: 36.6,
          payback_months: 24.4,
          cost_per_tonne_inr: -11420,
          added_grid_kwh: 45000,
        },
        {
          id: "item-4",
          sequence: 4,
          intervention_code: "SWARF_BRIQUETTING",
          title_en: "Hydraulic brass chip & swarf briquetting machine (250 kg/hr)",
          category: "circularity",
          pool: "brass_input_primary",
          difficulty: 2,
          circularity_points: 4,
          capex_inr: 405000,
          annual_savings_inr: 310000,
          reduction_kgco2e: 15400,
          reduction_tco2e: 15.4,
          payback_months: 15.7,
          cost_per_tonne_inr: -20129,
          added_grid_kwh: 0,
        },
      ],
      uncertainty: {
        savings_p10_inr: 2150000,
        savings_p90_inr: 2580000,
        payback_p10_months: 13.2,
        payback_p90_months: 16.0,
      },
    },
  ],
  macc: [
    {
      code: "CA_LEAK_FIX",
      title_en: "Compressed Air Leak Audit",
      tco2_cut: 24.6,
      cost_per_tonne_inr: -7805,
      capex_inr: 45000,
      annual_savings_inr: 192000,
      payback_months: 2.8,
      cumulative_tco2: 24.6,
      in_selected_plan: true,
    },
    {
      code: "CRUCIBLE_INSULATION",
      title_en: "Induction Crucible Insulation",
      tco2_cut: 18.2,
      cost_per_tonne_inr: -6593,
      capex_inr: 120000,
      annual_savings_inr: 240000,
      payback_months: 6.0,
      cumulative_tco2: 42.8,
      in_selected_plan: true,
    },
    {
      code: "VFD_COMPRESSOR",
      title_en: "Compressor VFD Retrofit",
      tco2_cut: 15.4,
      cost_per_tonne_inr: -13636,
      capex_inr: 185000,
      annual_savings_inr: 210000,
      payback_months: 10.5,
      cumulative_tco2: 58.2,
      in_selected_plan: true,
    },
    {
      code: "SOLAR_ROOFTOP_80KW",
      title_en: "80 kWp Solar Rooftop",
      tco2_cut: 84.4,
      cost_per_tonne_inr: -9928,
      capex_inr: 780000,
      annual_savings_inr: 838000,
      payback_months: 11.2,
      cumulative_tco2: 142.6,
      in_selected_plan: true,
    },
  ],
  frontier: [
    { capex_inr: 165000, reduction_tco2e: 42.8, mode: "quick_wins" },
    { capex_inr: 470000, reduction_tco2e: 68.4, mode: "low_capex" },
    { capex_inr: 1250000, reduction_tco2e: 142.6, mode: "balanced" },
    { capex_inr: 2850000, reduction_tco2e: 218.6, mode: "max_reduction" },
  ],
};

export const DEMO_TRACKING_DATA = {
  factory_id: DEMO_FACTORY_ID,
  active_plan_id: "plan-quick-wins",
  baseline_intensity: 0.79,
  current_intensity: 0.71,
  target_intensity: 0.53,
  progress_pct: 30.8,
  production_change_alert: false,
  production_change_pct: 2.1,
  adoptions: [
    {
      id: "adopt-1",
      factory_id: DEMO_FACTORY_ID,
      plan_item_id: "item-1",
      intervention_code: "CA_LEAK_FIX",
      title_en: "Compressed-air distribution leak audit & seal overhaul",
      category: "electricity",
      pool: "grid_electricity",
      status: "done",
      started_on: "2026-04-10",
      completed_on: "2026-04-28",
      actual_capex_inr: 42000,
      estimated_capex_inr: 45000,
      estimated_reduction_tco2e: 24.6,
      estimated_annual_savings_inr: 192000,
      notes: "Completed ultrasonic leak audit. Fixed 18 major drop-line coupler leaks.",
      sequence: 1,
    },
    {
      id: "adopt-2",
      factory_id: DEMO_FACTORY_ID,
      plan_item_id: "item-2",
      intervention_code: "CRUCIBLE_INSULATION",
      title_en: "Induction furnace ceramic fiber thermal insulation jacket",
      category: "electricity",
      pool: "grid_electricity",
      status: "in_progress",
      started_on: "2026-05-15",
      completed_on: null,
      actual_capex_inr: 60000,
      estimated_capex_inr: 120000,
      estimated_reduction_tco2e: 18.2,
      estimated_annual_savings_inr: 240000,
      notes: "Materials received from Ahmedabad refractory supplier. Installation scheduled during weekend shift.",
      sequence: 2,
    },
    {
      id: "adopt-3",
      factory_id: DEMO_FACTORY_ID,
      plan_item_id: "item-3",
      intervention_code: "SOLAR_ROOFTOP_80KW",
      title_en: "80 kWp On-site Solar PV Rooftop Installation",
      category: "onsite_solar",
      pool: "grid_electricity",
      status: "planned",
      started_on: null,
      completed_on: null,
      actual_capex_inr: null,
      estimated_capex_inr: 780000,
      estimated_reduction_tco2e: 84.4,
      estimated_annual_savings_inr: 838000,
      notes: "DISCOM net-metering application submitted to PGVCL Jamnagar circle.",
      sequence: 3,
    },
  ],
  trend: [
    { month: "2025-09", intensity: 0.79, is_recent: false },
    { month: "2025-10", intensity: 0.78, is_recent: false },
    { month: "2025-11", intensity: 0.76, is_recent: false },
    { month: "2025-12", intensity: 0.79, is_recent: false },
    { month: "2026-01", intensity: 0.81, is_recent: false },
    { month: "2026-02", intensity: 0.82, is_recent: false },
    { month: "2026-03", intensity: 0.84, is_recent: false },
    { month: "2026-04", intensity: 0.76, is_recent: true, completed_fixes: ["CA_LEAK_FIX"] },
    { month: "2026-05", intensity: 0.71, is_recent: true },
  ],
};

export const DEMO_LEVERS = [
  {
    code: "CA_LEAK_FIX",
    title_en: "Compressed-air distribution leak audit & seal overhaul",
    category: "electricity",
    pool: "grid_electricity",
    default_enabled: true,
    capex_inr: 45000,
    annual_savings_inr: 192000,
    reduction_tco2e: 24.6,
    difficulty: 1,
  },
  {
    code: "CRUCIBLE_INSULATION",
    title_en: "Induction furnace ceramic fiber thermal insulation jacket",
    category: "electricity",
    pool: "grid_electricity",
    default_enabled: true,
    capex_inr: 120000,
    annual_savings_inr: 240000,
    reduction_tco2e: 18.2,
    difficulty: 1,
  },
  {
    code: "VFD_COMPRESSOR",
    title_en: "Variable Frequency Drive (VFD) retrofit on 37kW screw compressor",
    category: "electricity",
    pool: "grid_electricity",
    default_enabled: false,
    capex_inr: 185000,
    annual_savings_inr: 210000,
    reduction_tco2e: 15.4,
    difficulty: 2,
  },
  {
    code: "SOLAR_ROOFTOP_80KW",
    title_en: "80 kWp On-site Solar PV Rooftop Installation (Net Metered)",
    category: "onsite_solar",
    pool: "grid_electricity",
    default_enabled: false,
    capex_inr: 780000,
    annual_savings_inr: 838000,
    reduction_tco2e: 84.4,
    difficulty: 2,
  },
  {
    code: "RECUPERATOR_FLUE",
    title_en: "Metallic recuperator for combustion air preheating on annealing line",
    category: "fuel",
    pool: "fuel_lpg",
    default_enabled: false,
    capex_inr: 305000,
    annual_savings_inr: 210000,
    reduction_tco2e: 15.4,
    difficulty: 2,
  },
];
